spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
    show-sql: true
    open-in-view: true

  config:
    activate:
      on-profile: local
    import:
      application-secret.yml